services:
  superlink:
    image: flwr/superlink:1.22.0
    container_name: superlink
    networks:
      - flwr-network
    ports:
      - "9093:9093"
      - "9092:9092"
    volumes:
      - ./certificates:/certificates:ro
    command:
      - --ssl-ca-certfile=/certificates/ca/ca.crt
      - --ssl-certfile=/certificates/server/server.crt
      - --ssl-keyfile=/certificates/server/server.key
    restart: unless-stopped

  supernode-0:
    image: flwr/supernode:1.22.0
    container_name: supernode-0
    networks:
      - flwr-network
    volumes:
      - ./certificates:/certificates:ro
      - ./quickstart-docker:/app
    command:
      - --root-certificates=/certificates/ca/ca.crt
      - --superlink=superlink:9092
      - --clientappio-api-address=0.0.0.0:9094
      - --node-config=partition-id=0 num-partitions=2
    depends_on:
      - superlink
    restart: unless-stopped

  supernode-1:
    image: flwr/supernode:1.22.0
    container_name: supernode-1
    networks:
      - flwr-network
    volumes:
      - ./certificates:/certificates:ro
      - ./quickstart-docker:/app
    command:
      - --root-certificates=/certificates/ca/ca.crt
      - --superlink=superlink:9092
      - --clientappio-api-address=0.0.0.0:9095
      - --node-config=partition-id=1 num-partitions=2
    depends_on:
      - superlink
    restart: unless-stopped

networks:
  flwr-network:
    external: true
